### ISSUE TITLE
Can't open a solution (.sln)

### ISSUE THREAD

**Issue by gilbertoca** [Chris2011/CSharp-for-netbeans#1]
Can't open a solution (.sln) ..
![captura de tela_2016-10-18_10-02-27](https://cloud.githubusercontent.com/assets/3083703/19478611/a30b90de-9519-11e6-8452-22b99678319e.png)

**Comment by Chris2011** [comment]
Thx let me Check it. I think the Problem is because of the Name of the sln File which is not the same of the parent folder (src).
I didn't notice such Case but I will.

Only as a hint this Project is in development. There is no Syntax Highlighting or some othet stuff at all. Only to let you know.

**Comment by gilbertoca** [comment]
Ok, thank you for sharing the experience and effort in the project. Hope to help as well!
I'm doing code review in both Java and C#. Definitely this plugin will come in handy.

**Comment by Chris2011** [comment]
Yes but it is a looooong way to go. Can you do me a favor and make a little test solution like your image above with sub projects and an other folder name, such a little real case scenario for me to check what is wrong and your expectation what you expect what should my plugin does? Is this possible?

**Comment by gilbertoca** [comment]
I'm trying to open this https://github.com/BoletoNet/boletonet project. Like a java/maven project, I would like to navigate between artifacts and if possible compile and run it. I've setup [dotnet](https://www.microsoft.com/net/core#opensuse):

```
[10:20] gilberto.andrade@BEM-INF007:src (master *% u=) $ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     opensuse
 OS Version:  42.1
 OS Platform: Linux
 RID:         opensuse.42.1-x64
```

I didn't understand your question.  Would you mind explaining?
I'm using Netbeans 8.2
Open the Solution filet after renaming it to src:
![screenshot_20161019_115839](https://cloud.githubusercontent.com/assets/3083703/19524123/14afd7e8-95f3-11e6-985a-471c57e54c24.png)

**Comment by Chris2011** [comment]
Everything is fine, I will check it. Please for now, you can't use my plugin for production as you want. Try to use monodevelop or Visual Studio Code for Linux. Next big step will be the syntax highlighting. (Hopefully).

**Comment by Chris2011** [comment]
Can you please deactivate my plugin first, I think there are some more problems. I installed the 0.0.0.1 release nbm file and my whole UI in the IDE is broken. Is this a problem for you too? It seems so in the screen. So for now it is really unstable. I don't know atm whether it is a problem with 8.2 or not.

**Comment by gilbertoca** [comment]
Yes, I believe so.  I will wait some progress of your part before try it again.

**Comment by Chris2011** [comment]
Thx for your understanding :)

**Comment by Chris2011** [comment]
So I fixed this bug, now you can open folders with sln files inide, doesn't matter the name and for projects with csproj files too. Atm you can't open cs files, because I'm trying to implement syntaxx highlighting. I will create a 0.0.0.2 build soon for you only to test this ticket again and to check it out. Thx for reporting.

**Comment by Chris2011** [comment]
If there is another problem when you would like to open a folder within a sln file, which should work in Visual Studio, dann please reopen the ticket with maybe the repo which you tested.

**Comment by Chris2011** [comment]
Please test and verify the bugfix. Thx.
https://github.com/Chris2011/CSharp-for-netbeans/releases/tag/0.0.0.2

**Comment by gilbertoca** [comment]
8.1 and 8.2
![screenshot_20161028_094509](https://cloud.githubusercontent.com/assets/3083703/19807083/309b9404-9cfd-11e6-80a8-a3496ac627b3.png)

![screenshot_20161028_094719](https://cloud.githubusercontent.com/assets/3083703/19807093/3cf0e1fa-9cfd-11e6-861a-d8df5a6c1eaa.png)

But I can't open any cs file

![screenshot_20161028_095412](https://cloud.githubusercontent.com/assets/3083703/19807105/4f08bd68-9cfd-11e6-8b96-11c6dc44d3a4.png)

After confirming, the Editor opens and quickly closes.

**Comment by Chris2011** [comment]
But the original error is gone for you?

As I said in my comment https://github.com/Chris2011/CSharp-for-netbeans/issues/1#issuecomment-256569302: ...Atm you can't open cs files, because I'm trying to implement syntaxx highlighting....

**Comment by Chris2011** [comment]
So yes I know the problem but for now, it is an other problem. Please create a ticket for thix if you want.
