### ISSUE TITLE
Projects-Tab not working correctly for empty project

### ISSUE THREAD

**Issue by prayzzz** [Chris2011/CSharp-for-netbeans#11]
I created a new solution with a class library.

The Projects-Tab is showing the class library twice and "Please wait" but nothing happens.

![newsolution](https://cloud.githubusercontent.com/assets/9248359/20244511/f53123f8-a985-11e6-90d5-e7506bc9f2cf.PNG)

Edit:
* ClassLibrary is not added to *.sln file.
* *.csproj file contains no valid content

**Comment by Chris2011** [comment]
I think it will throw a NPE. I will check it and fix it. Thx.

**Comment by Chris2011** [comment]
That the ClassLib is opening too, is in case of the handling of NetBeans with submodules. It is like a maven based multiple module project So The sln is the container for the modules and the others are the modules so NetBeans will always open the sub modules as separate projects too. Maybe I can prevent that but this will be an other issue.

**Comment by Chris2011** [comment]
For the thing with ClassLib is not part of sln file, yes the problem is that I didn't parse the sln file and not read/write anything into and from it except create a solution, nothing more. I will change this.

Ticket: https://github.com/Chris2011/CSharp-for-netbeans/issues/15

**Comment by Chris2011** [comment]
Fixed the NPE for SubModules with nothing inside.
