### ISSUE TITLE
State of plugin

### ISSUE THREAD

**Issue by detectivejd** [Chris2011/CSharp-for-netbeans#17]
Hi, I wanted to ask in what state is the C # plugin developed for netbeans?

Can web and desktop applications be made in netbeans?

This plugin is useful in windows, linux and mac?

Greetings.

**Comment by Chris2011** [comment]
Hi,

thx for your interests. Atm it is not possible to create any application. You can create a sln which is not complete. It was needed to test the plugin. I didn't find time until now to do much more work, so Im searching for helping hands and will be more active in the next months. The goal is, that it should work in Windows, Linux and mac, yes. 


Regards

Chris

**Comment by detectivejd** [comment]
Ok, I'll be aware of the state of this plugin. Regards.
