### ISSUE TITLE
Can't open or view any cs file

### ISSUE THREAD

**Issue by gilbertoca** [Chris2011/CSharp-for-netbeans#2]
Both 8.1 and 8.2 of NetBeans

![screenshot_20161028_095412](https://cloud.githubusercontent.com/assets/3083703/19807637/d44d1ba2-9cff-11e6-918a-c9eb0016bf26.png)

After confirming, the Editor opens and quickly closes.

**Comment by Chris2011** [comment]
The problem is, that I'm working on the lexer for syntax highlighting. I could comment the stuff out, who produces the error and can make it on a feature branch, but without having syntax highlighting, you only have plain text.

**Comment by Chris2011** [comment]
I added basic syntax highlighting in release 0.0.0.3: https://github.com/Chris2011/CSharp-for-netbeans/releases/tag/0.0.0.3 Please test and if everything ok, then close the ticket. :)

Thx for reporting.

**Comment by gilbertoca** [comment]
It is ok
![screenshot_20161029_104031](https://cloud.githubusercontent.com/assets/3083703/19829935/6ee6b46c-9dcc-11e6-97d5-1a0ab266ea13.png)
